# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
copyright: © Blog Brecht Billiet - All rights reserved

# Author
author_image: brecht.png
author_name: Brecht Billiet
author_url: http://brecht.io
author_bio: Software architect/trainer/coach/speaker/blogger

# Name of your site (displayed in the header)
name: Brecht Billiet
title: Frontend software architect living in Belgium
email: billietbrecht@gmail.com
description: ''
hero_image: hero.png
logo_url: img/brecht.png
sub_title: Brecht Billiet

# Social Settings
twitter_username: http://twitter.com/brechtbilliet
github_username: http://github.com/brechtbilliet
linkedin_username: https://www.linkedin.com/in/brecht-billiet-58417426
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://blog.brecht.io'
permalink: /:title/
disqus:
  shortname: brechtbilliet

# Build settings
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-43296458-5
google_verification:
disqus-shortname: brechtbilliet
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
